### ISSUE TITLE
Resource not found for the segment (...)

### ISSUE THREAD

**Issue by JanPetterMG** [TheNetworg/oauth2-azure#77]
Trying to use this library for the first time, but I always get `Resource not found for the segment (...).` no matter what I try. It's probably something obvious I am missing here.

Following the [coding flow example](https://github.com/TheNetworg/oauth2-azure#authorization-code-flow) in the readme. `$provider->get("me", $token);` works, but everything else gives me the following error.

````
Fatal error:
Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: Resource 'calendars' does not exist or one of its queried reference-property objects are not present. in /vendor/thenetworg/oauth2-azure/src/Provider/Azure.php:315
Stack trace:
#0 /vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): TheNetworg\OAuth2\Client\Provider\Azure->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 /vendor/thenetworg/oauth2-azure/src/Provider/Azure.php(173): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 /vendor/thenetworg/oauth2-azure/src/Provider/Azure.php(104): TheNetworg\OAuth2\Client\Provider\Azure->request('get', 'd8aa4b66-c36f-4...', Object(TheNetworg\OAuth2\Client\Token\AccessToken), Array)
#3 (...)/test.php(64): TheNetworg\OAuth2\Client\Provider\Azure->get('/me/calendars', Object(TheNetworg\OAuth2\Client\Token\AccessToken))
#4 {main}
thrown in /vendor/thenetworg/oauth2-azure/src/Provider/Azure.php on line 315
````

Trying to access the calendar API at https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0 but can't get any request paths to work. Tried a variety of different URL combinations, relative/absolute paths as well as full URLs.

Tried both `https://graph.windows.net` and `https://graph.microsoft.com` as access token resources.

 Any suggestions?

**Comment by JanPetterMG** [comment]
Seems like I forgot these two lines:
```
$provider->urlAPI = "https://graph.microsoft.com/v1.0/";
$provider->resource = "https://graph.microsoft.com/";
```
