### ISSUE TITLE
League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant

### ISSUE THREAD

**Issue by akovacs123** [TheNetworg/oauth2-azure#89]
I fetched the code and copied the example with no change. I authenticate using O365 and they I get my personal information just fine. When refeshing the page I get the following error when calling `getAccessToken`:

`Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /var/www/<sitename>/httpdocs/o365/thenetworg/vendor/thenetworg/oauth2-azure/src/Provider/Azure.php:317 Stack trace: #0 /var/www/<sitename>/httpdocs/o365/thenetworg/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): TheNetworg\OAuth2\Client\Provider\Azure->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /var/www/<sitename>/httpdocs/o365/thenetworg/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /var/www/<sitename>/httpdocs/o365/thenetworg/vendor/thenetworg/oauth2-azure/src/Provider/Azure.php(59): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array) #3 /var/www/<sitename>/httpdocs/o365/thenetworg/index.php(43): TheNetworg\OAuth2\Client\Provider\Azure in /var/www/<sitename>/httpdocs/o365/thenetworg/vendor/thenetworg/oauth2-azure/src/Provider/Azure.php on line 317`

The error message from O365 is the following:

`Array(
    [error] => invalid_grant
    [error_description] => AADSTS70008: The provided authorization code or refresh token is expired. Send a new interactive authorization request for this user and resource.
Trace ID: 9b56a074-9953-491b-acbc-bc9be2e5b200
Correlation ID: f9847fe0-ce6e-45ae-8389-93eee3006a8e
Timestamp: 2019-07-08 21:14:24Z
    [error_codes] => Array
        (
            [0] => 70008
        )
    [timestamp] => 2019-07-08 21:14:24Z
    [trace_id] => 9b56a074-9953-491b-acbc-bc9be2e5b200
    [correlation_id] => f9847fe0-ce6e-45ae-8389-93eee3006a8e
)`

Is refresh token handled incorrectly?

The provider object looks like this:

`TheNetworg\OAuth2\Client\Provider\Azure Object
(
    [urlLogin] => https://login.microsoftonline.com/
    [pathAuthorize] => /oauth2/authorize
    [pathToken] => /oauth2/token
    [scope] => Array
        (
        )

    [scopeSeparator] =>  
    [tenant] => common
    [urlAPI] => https://graph.windows.net/
    [resource] => 
    [API_VERSION] => 1.6
    [authWithResource] => 1
    [clientId:protected] => 80123f11-fe89-4aa0-9f99-845d4cfe9fe9
    [clientSecret:protected] => <snip>
    [redirectUri:protected] => https://<sitename>/o365/
    [state:protected] => 
    [grantFactory:protected] => League\OAuth2\Client\Grant\GrantFactory Object
        (
            [registry:protected] => Array
                (
                    [jwt_bearer] => TheNetworg\OAuth2\Client\Grant\JwtBearer Object
                        (
                        )

                )

        )

    [requestFactory:protected] => League\OAuth2\Client\Tool\RequestFactory Object
        (
        )

    [httpClient:protected] => GuzzleHttp\Client Object
        (
            [config:GuzzleHttp\Client:private] => Array
                (
                    [handler] => GuzzleHttp\HandlerStack Object
                        (
                            [handler:GuzzleHttp\HandlerStack:private] => Closure Object
                                (
                                    [static] => Array
                                        (
                                            [default] => Closure Object
                                                (
                                                    [static] => Array
                                                        (
                                                            [default] => GuzzleHttp\Handler\CurlMultiHandler Object
                                                                (
                                                                    [factory:GuzzleHttp\Handler\CurlMultiHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                        (
                                                                            [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
                                                                                (
                                                                                )

                                                                            [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 50
                                                                        )

                                                                    [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private] => 1
                                                                    [active:GuzzleHttp\Handler\CurlMultiHandler:private] => 
                                                                    [handles:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                        (
                                                                        )

                                                                    [delays:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                        (
                                                                        )

                                                                )

                                                            [sync] => GuzzleHttp\Handler\CurlHandler Object
                                                                (
                                                                    [factory:GuzzleHttp\Handler\CurlHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                        (
                                                                            [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
                                                                                (
                                                                                )

                                                                            [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 3
                                                                        )

                                                                )

                                                        )

                                                    [parameter] => Array
                                                        (
                                                            [$request] => 
                                                            [$options] => 
                                                        )

                                                )

                                            [streaming] => GuzzleHttp\Handler\StreamHandler Object
                                                (
                                                    [lastHeaders:GuzzleHttp\Handler\StreamHandler:private] => Array
                                                        (
                                                        )

                                                )

                                        )

                                    [parameter] => Array
                                        (
                                            [$request] => 
                                            [$options] => 
                                        )

                                )

                            [stack:GuzzleHttp\HandlerStack:private] => Array
                                (
                                    [0] => Array
                                        (
                                            [0] => Closure Object
                                                (
                                                    [parameter] => Array
                                                        (
                                                            [$handler] => 
                                                        )

                                                )

                                            [1] => http_errors
                                        )

                                    [1] => Array
                                        (
                                            [0] => Closure Object
                                                (
                                                    [parameter] => Array
                                                        (
                                                            [$handler] => 
                                                        )

                                                )

                                            [1] => allow_redirects
                                        )

                                    [2] => Array
                                        (
                                            [0] => Closure Object
                                                (
                                                    [parameter] => Array
                                                        (
                                                            [$handler] => 
                                                        )

                                                )

                                            [1] => cookies
                                        )

                                    [3] => Array
                                        (
                                            [0] => Closure Object
                                                (
                                                    [parameter] => Array
                                                        (
                                                            [$handler] => 
                                                        )

                                                )

                                            [1] => prepare_body
                                        )

                                )

                            [cached:GuzzleHttp\HandlerStack:private] => 
                        )

                    [allow_redirects] => Array
                        (
                            [max] => 5
                            [protocols] => Array
                                (
                                    [0] => http
                                    [1] => https
                                )

                            [strict] => 
                            [referer] => 
                            [track_redirects] => 
                        )

                    [http_errors] => 1
                    [decode_content] => 1
                    [verify] => 1
                    [cookies] => 
                    [headers] => Array
                        (
                            [User-Agent] => GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u3
                        )

                )

        )

    [optionProvider:protected] => League\OAuth2\Client\OptionProvider\PostAuthOptionProvider Object
        (
        )

    [guarded:protected] => Array
        (
        )

)
`

What am I doing wrong? Thanks

**Comment by nationdata-it** [comment]
Not sure if same issue I was having, but you cannot just refresh the page, you need to try loading the page without all the URL params received after login.  So if you're testing on http://localhost, when you first login then return back to localhost, your URL is like:

http://localhost/?code=347fhdhdfgjdd.....

just change your URL to:
http://localhost/

you should then see the standard user details "Hello {NAME}".

Hope it helps :)
